import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Hello Next Example",
  description: "Generated by create-next-app",
  icons: {
    icon: "/favicon.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="bg-red-300 p-5">
          <h2>Header</h2>
        </header>
  <div className="p-16">
  {children}
  </div>
        <footer className="bg-blue-300 p-5 text-center">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
