import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Hello Next Example",
  description: "Generated by create-next-app",
  icons: {
    icon: "/favicon.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
